gowobble:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - /var/wobble:/go/src/wobblapp
  links:
    - wobbledb

wobbledb:
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null
