gowooble:
  build: .
  container_name: gowooble
  dockerfile: Dockerfile.service
  ports:
    - "3000:3000"
  volumes:
    - $PWD:/go/src/wooble
  links:
    - woobledb

woobledb:
  build: .
  container_name: woobledb
  dockerfile: Dockerfile.db
  ports:
    - "5432:5432"
