gowooble:
  build: .
  dockerfile: Dockerfile.service
  ports:
    - "4000:4000"
  volumes:
    - $PWD:/go/src/wooble
  links:
    - woobledb

woobledb:
  build: .
  dockerfile: Dockerfile.db
  ports:
    - "5432:5432"
