gowooble:
  build: .
  dockerfile: Dockerfile.service
  ports:
    - "3000:3000"
  volumes:
    - $PWD:/go/src/wooblapp
  links:
    - woobledb

woobledb:
  build: .
  dockerfile: Dockerfile.db
  ports:
    - "5432:5432"
