gowooble:
  build: .
  ports:
    - "3000:3000"
  volumes:
    - $PWD:/go/src/wooblapp
  links:
    - woobledb

woobledb:
  image: mongo:3.0
  command: mongod --smallfiles --quiet --logpath=/dev/null
