FROM postgres:9.5

ENV POSTGRES_USER wooble
ENV POSTGRES_PASSWORD w00b

RUN touch dump.sh && \
echo 'pg_dump --file "/schema.sql" --username "wooble" --no-password --verbose --role "wooble" --format=p --encoding "UTF8" "wooble"' > dump.sh

ADD ./conf/init_db.sh /docker-entrypoint-initdb.d/
ADD ./conf/schema.sql /
