# DB config
db_host: woobledb
db_name: wooble
db_port: 5432
db_username: wooble
db_password: w00b

# Third parties config
cloud_repo: wooble-dev
pkg_repo: wooble-pkg-dev
stripe_key: <stripe key>

# Server config
token_key: abcd1234
enc_key: 1234abcd1234abcd1234abcd
token_lifetime: 30 # minutes
keygen_range: abcdefghijklmnopqrstuvwxyz0123456789
salt_for_id: hello
allow_origin:
  - http://localhost:4000
  - http://localhost:4200
pkg_url: https://d2ncq0durb0run.cloudfront.net

# Email config
email_host: ssl0.ovh.net:587
email_passwd: Duny10260
